### ISSUE TITLE
Ibexa 4.6 has new service definitions that break ResultExtractor and IndexableRichText

### ISSUE THREAD

**Issue by wizhippo** [netgen/ibexa-search-extra#7]
RichTextIndexablePass should remove all arguments then add its single argument as upstream there are now multiple arguments in the base service.

ResultExtractor::Extract now has a new argument that need to be added to the netgen version.

**Comment by pspanja** [comment]
Accidentally fixed in https://github.com/netgen/ibexa-search-extra/commit/9af5bf68ebe9dc332b78435160bdda3b0abb2446
